import json
import subprocess
import sys
from pathlib import Path

SCRIPT = Path(__file__).resolve().parent.parent / "scripts" / "roadmap_merge.py"


def run_script(args, stdin_text=None):
    result = subprocess.run(
        [sys.executable, str(SCRIPT), *args],
        capture_output=True, text=True, input=stdin_text
    )
    return result.stdout, result.stderr, result.returncode


def test_no_args_shows_usage():
    out, err, code = run_script([])
    assert code != 0
    combined = (out + err).lower()
    assert "usage" in combined or "subcommand" in combined


def test_help_lists_three_subcommands():
    out, err, code = run_script(["--help"])
    combined = out + err
    assert "parse" in combined
    assert "merge" in combined
    assert "render" in combined


def test_unknown_subcommand_errors():
    out, err, code = run_script(["bogus"])
    assert code != 0


SAMPLE_ROADMAP = """# Publishing Roadmap

> Generated by `chart-publishing-path` on 2026-05-14.

**Platforms:** Apple App Store, Google Play
**App:** Acme Mobile (`com.acme.mobile`)
**Framework:** Expo SDK 52 / React Native 0.76 (managed)
**Last audit:** 2026-05-14

## Summary

- ✅ Done: 1
- ⬜ Pending: 1

---

## 1. Account & Developer Program

- ✅ [Both] Developer accounts active — both stores show paid/active. <!-- id: shared.account.dev-program -->
- ⬜ [Apple] Tax & banking info — not yet completed. <!-- id: apple.account.tax-banking -->
  > _Dev note (2026-05-10): waiting on accountant._

## 2. App Identity & Versioning

- ✅ [Both] `app.json` declares bundle identifier. <!-- id: shared.identity.bundle-id -->

---

## Notes & history

- 2026-05-14 — Initial scaffold (Expo 52, RN 0.76).
"""


def test_parse_empty_file(tmp_path):
    f = tmp_path / "roadmap.md"
    f.write_text("", encoding="utf-8")
    out, _, code = run_script(["parse", str(f)])
    assert code == 0
    state = json.loads(out)
    assert state["items"] == []
    assert state["history"] == []


def test_parse_missing_file_errors(tmp_path):
    f = tmp_path / "nope.md"
    out, err, code = run_script(["parse", str(f)])
    assert code != 0


def test_parse_header_fields(tmp_path):
    f = tmp_path / "roadmap.md"
    f.write_text(SAMPLE_ROADMAP, encoding="utf-8")
    out, _, code = run_script(["parse", str(f)])
    assert code == 0
    state = json.loads(out)
    assert state["header"]["app_name"] == "Acme Mobile"
    assert state["header"]["bundle_id"] == "com.acme.mobile"
    assert "Apple App Store" in state["header"]["platforms"]
    assert "Google Play" in state["header"]["platforms"]
    assert state["header"]["last_audit"] == "2026-05-14"
    assert "Expo SDK 52" in state["header"]["framework"]


def test_parse_items_with_ids(tmp_path):
    f = tmp_path / "roadmap.md"
    f.write_text(SAMPLE_ROADMAP, encoding="utf-8")
    out, _, code = run_script(["parse", str(f)])
    state = json.loads(out)
    ids = [it["id"] for it in state["items"]]
    assert "shared.account.dev-program" in ids
    assert "apple.account.tax-banking" in ids
    assert "shared.identity.bundle-id" in ids


def test_parse_status_icons(tmp_path):
    f = tmp_path / "roadmap.md"
    f.write_text(SAMPLE_ROADMAP, encoding="utf-8")
    out, _, code = run_script(["parse", str(f)])
    state = json.loads(out)
    by_id = {it["id"]: it for it in state["items"]}
    assert by_id["shared.account.dev-program"]["status"] == "done"
    assert by_id["apple.account.tax-banking"]["status"] == "pending"


def test_parse_section_assignment(tmp_path):
    f = tmp_path / "roadmap.md"
    f.write_text(SAMPLE_ROADMAP, encoding="utf-8")
    out, _, code = run_script(["parse", str(f)])
    state = json.loads(out)
    by_id = {it["id"]: it for it in state["items"]}
    assert by_id["shared.account.dev-program"]["section"] == 1
    assert by_id["shared.identity.bundle-id"]["section"] == 2


def test_parse_platform_tags(tmp_path):
    f = tmp_path / "roadmap.md"
    f.write_text(SAMPLE_ROADMAP, encoding="utf-8")
    out, _, code = run_script(["parse", str(f)])
    state = json.loads(out)
    by_id = {it["id"]: it for it in state["items"]}
    assert by_id["shared.account.dev-program"]["platform_tag"] == "Both"
    assert by_id["apple.account.tax-banking"]["platform_tag"] == "Apple"


def test_parse_dev_note_preserved(tmp_path):
    f = tmp_path / "roadmap.md"
    f.write_text(SAMPLE_ROADMAP, encoding="utf-8")
    out, _, code = run_script(["parse", str(f)])
    state = json.loads(out)
    by_id = {it["id"]: it for it in state["items"]}
    notes = by_id["apple.account.tax-banking"]["dev_notes"]
    assert len(notes) == 1
    assert notes[0]["date"] == "2026-05-10"
    assert "waiting on accountant" in notes[0]["text"]


def test_parse_history_log(tmp_path):
    f = tmp_path / "roadmap.md"
    f.write_text(SAMPLE_ROADMAP, encoding="utf-8")
    out, _, code = run_script(["parse", str(f)])
    state = json.loads(out)
    assert len(state["history"]) == 1
    assert state["history"][0]["date"] == "2026-05-14"
    assert "Initial scaffold" in state["history"][0]["text"]


def test_parse_item_without_id_comment_ignored(tmp_path):
    f = tmp_path / "roadmap.md"
    f.write_text("""# Publishing Roadmap

## 1. Account & Developer Program

- ✅ [Both] Some item with no ID comment.
- ⬜ [Apple] Another with no ID. <!-- not-an-id-comment -->
""", encoding="utf-8")
    out, _, code = run_script(["parse", str(f)])
    assert code == 0
    state = json.loads(out)
    assert state["items"] == []
