# scripts/status_update.py
"""STATUS.md helper for the probe-feature skill library.

Owns all reads/writes of docs/features/<slug>/issues/STATUS.md.
Subcommands: seed, mark-executed, mark-verified, regen, next.

The Notes section is user-owned and always preserved verbatim.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DASH = "—"
TABLE_HEADER = "| Issue | Slice | Executed | Verified |"
TABLE_SEP = "|-------|-------|----------|----------|"


def issue_files(issues_dir: Path):
    """Return sorted list of NNN-*.md issue stems (excludes STATUS/SEQUENCE)."""
    out = []
    for p in sorted(issues_dir.glob("[0-9][0-9][0-9]-*.md")):
        if p.name in ("STATUS.md", "SEQUENCE.md"):
            continue
        out.append(p)
    return out


def slice_type_of(issue_path: Path) -> str:
    for line in issue_path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"##\s*Slice type:\s*(\S+)", line)
        if m:
            return m.group(1).strip()
    return "vertical"


def parse_notes(status_path: Path) -> str:
    """Extract the body after the '## Notes' heading, or a default."""
    if not status_path.exists():
        return "<freeform; preserved across regenerations>\n"
    text = status_path.read_text(encoding="utf-8")
    idx = text.find("\n## Notes")
    if idx == -1:
        return "<freeform; preserved across regenerations>\n"
    body = text[idx + len("\n## Notes"):].lstrip("\n")
    return body if body.strip() else "<freeform; preserved across regenerations>\n"


def parse_rows(status_path: Path) -> dict:
    """Return {issue_stem: {'slice':, 'executed':, 'verified':}} from an
    existing STATUS.md table. Empty dict if no file/table."""
    rows = {}
    if not status_path.exists():
        return rows
    for line in status_path.read_text(encoding="utf-8").splitlines():
        if not line.startswith("| "):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) != 4 or cells[0] in ("Issue", "-------"):
            continue
        if set(cells[0]) <= set("-"):
            continue
        rows[cells[0]] = {
            "slice": cells[1],
            "executed": cells[2],
            "verified": cells[3],
        }
    return rows


def render(name: str, slug: str, ordered_stems: list, rows: dict, notes: str) -> str:
    n = len(ordered_stems)
    n_exec = sum(1 for s in ordered_stems if rows[s]["executed"] != DASH)
    n_ver = sum(1 for s in ordered_stems if rows[s]["verified"] != DASH)
    all_pass = n > 0 and all(
        rows[s]["verified"].endswith("PASS") for s in ordered_stems
    )
    feat = "complete" if all_pass else (
        f"in-progress — {n_exec}/{n} executed, {n_ver}/{n} verified"
    )
    lines = [
        f"# Status — {name} ({slug})",
        "",
        "Generated by slice-issues; updated by execute-issue / verify-issue.",
        "Do not hand-edit the table. The Notes section is yours and is preserved.",
        "",
        TABLE_HEADER,
        TABLE_SEP,
    ]
    for s in ordered_stems:
        r = rows[s]
        lines.append(f"| {s} | {r['slice']} | {r['executed']} | {r['verified']} |")
    lines += ["", f"**Feature status:** {feat}", "", "## Notes", "", notes.rstrip() + "\n"]
    return "\n".join(lines)


def load_state(feature_dir: Path):
    issues_dir = feature_dir / "issues"
    status_path = issues_dir / "STATUS.md"
    stems = [p.stem for p in issue_files(issues_dir)]
    old = parse_rows(status_path)
    rows = {}
    for stem in stems:
        prev = old.get(stem, {})
        rows[stem] = {
            "slice": slice_type_of(issues_dir / f"{stem}.md"),
            "executed": prev.get("executed", DASH),
            "verified": prev.get("verified", DASH),
        }
    return issues_dir, status_path, stems, rows


def write_status(args, transform=None):
    feature_dir = Path(args.feature_dir)
    issues_dir, status_path, stems, rows = load_state(feature_dir)
    if not stems:
        print(f"No issue files in {issues_dir}", file=sys.stderr)
        return 1
    if transform:
        err = transform(rows)
        if err:
            print(err, file=sys.stderr)
            return 1
    notes = parse_notes(status_path)
    status_path.write_text(
        render(args.name, args.slug, stems, rows, notes), encoding="utf-8"
    )
    print(f"Wrote {status_path}")
    return 0


def cmd_seed(args):
    return write_status(args)


def _require_issue(rows, stem):
    if stem not in rows:
        return f"Issue '{stem}' not found among issue files."
    return None


def cmd_mark_executed(args):
    def t(rows):
        err = _require_issue(rows, args.issue)
        if err:
            return err
        val = args.date
        if args.status and args.status != "DONE":
            val = f"{args.date} {args.status}"
        rows[args.issue]["executed"] = val
        return None
    return write_status(args, t)


def cmd_mark_verified(args):
    def t(rows):
        err = _require_issue(rows, args.issue)
        if err:
            return err
        rows[args.issue]["verified"] = f"{args.date} {args.verdict}"
        return None
    return write_status(args, t)


def build_parser():
    p = argparse.ArgumentParser(description="STATUS.md helper")
    sub = p.add_subparsers(dest="cmd", required=True)

    sp = sub.add_parser("seed", help="Create/refresh STATUS.md from issue files")
    sp.add_argument("--feature-dir", required=True)
    sp.add_argument("--name", required=True)
    sp.add_argument("--slug", required=True)
    sp.set_defaults(func=cmd_seed)

    me = sub.add_parser("mark-executed", help="Set the Executed cell")
    me.add_argument("--feature-dir", required=True)
    me.add_argument("--name", required=True)
    me.add_argument("--slug", required=True)
    me.add_argument("--issue", required=True, help="Issue stem, e.g. 001-alpha")
    me.add_argument("--date", required=True)
    me.add_argument("--status", choices=["DONE", "BLOCKED", "NEEDS_USER"],
                    default="DONE")
    me.set_defaults(func=cmd_mark_executed)

    mv = sub.add_parser("mark-verified", help="Set the Verified cell")
    mv.add_argument("--feature-dir", required=True)
    mv.add_argument("--name", required=True)
    mv.add_argument("--slug", required=True)
    mv.add_argument("--issue", required=True, help="Issue stem, e.g. 001-alpha")
    mv.add_argument("--date", required=True)
    mv.add_argument("--verdict", required=True,
                    choices=["PASS", "FAIL", "NEEDS_USER"])
    mv.set_defaults(func=cmd_mark_verified)

    return p


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
